config/routes.rb
Rails.application.routes.draw do
  resources :talks

  resources :products

  get 'talks/list/:owner_id' => 'talks#list'
  
  post 'talks/list/:owner_id' => 'talks#create_talk'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
  end

  # GET /talks/new
  def new
    @talk = Talk.new
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talks/1
  # PATCH/PUT /talks/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render :edit }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to talks_url, notice: 'Talk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #talks Method

  def list
    @talks = Talk.where(owner_id: params[:owner_id]).order("id desc").limit(params[:size])
    @params = params
    @talk = Talk.new
    respond_to do |format|
      format.html { render :list }
      format.json { render json: @talks}
    end
  end  

  def create_talk
    @talk = Talk.new(params.require(:talk).permit(:nickname, :content))
    @talk.writed_date = DateTime.now
    @talk.owner_id = params[:owner_id]

    respond_to do |format|
      if @talk.save
        format.html { redirect_to "/talks/list/#{params[:owner_id]}" }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talk_params
      params.require(:talk).permit(:writer_id, :nickname, :content, :writed_date, :ip_address, :owner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductTalk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :writer_id %><br>
    <%= f.text_field :writer_id %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :writed_date %><br>
    <%= f.date_select :writed_date %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/_form_inline.html.erb
<%= form_for @talk, html: {method: "post"}, url: "/talks/list/#{params[:owner_id]}" do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<h1>Listing talks</h1>

<table>
  <thead>
    <tr>
      <th>Writer</th>
      <th>Nickname</th>
      <th>Content</th>
      <th>Writed date</th>
      <th>Ip address</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
      <tr>
        <td><%= talk.writer_id %></td>
        <td><%= talk.nickname %></td>
        <td><%= talk.content %></td>
        <td><%= talk.writed_date %></td>
        <td><%= talk.ip_address %></td>
        <td><%= talk.owner_id %></td>
        <td><%= link_to 'Show', talk %></td>
        <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
        <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/list.html.erb
<h1>Owner Id : <%= params[:owner_id] %></h1>

<%= render 'form_inline' %>

<table>
  <thead>
    <tr>
      <th>Writer</th>
      <th>Nickname</th>
      <th>Content</th>
      <th>Writed date</th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
      <tr>
        <td><%= talk.writer_id %></td>
        <td><%= talk.nickname %></td>
        <td><%= talk.content %></td>
        <td><%= talk.writed_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/talks/new.html.erb
<h1>New talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Writer:</strong>
  <%= @talk.writer_id %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @talk.nickname %>
</p>

<p>
  <strong>Content:</strong>
  <%= @talk.content %>
</p>

<p>
  <strong>Writed date:</strong>
  <%= @talk.writed_date %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @talk.ip_address %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @talk.owner_id %>
</p>

<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>